# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-08 23:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20161008_2240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whatwedo',
            options={'ordering': ['-create_date', '-updated']},
        ),
        migrations.AddField(
            model_name='whatwedo',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2016, 10, 8, 23, 12, 24, 631955, tzinfo=utc), unique=True),
            preserve_default=False,
        ),
    ]
