# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-12 23:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_ourboard_ourteam_volunteriing'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Volunteriing',
            new_name='Volunterring',
        ),
    ]
