# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-13 02:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_home'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
    ]
