# This script will provision your public SSH key onto the remote machine for the admin and cms users.
---

- hosts: ubuntu14-test
  user: '{{rootuser}}'

  vars_files:
    - vars/vagrant_variables.yml

  vars:
    ansible_ssh_user: '{{rootuser}}'                         # We need to override this to use the admin user as
                                                              # the root account will be locked by this point

  tasks:

  # Setup an public key for this remote machine by copying the public key of this machine to the remote machine.
  # We need to have our id_rsa.pub file within your home directory.
  - name: Add My Public Key To CMS and Admin Users
    authorized_key: user={{ item }}
      key="{{ lookup('file', ubuntu_common_deploy_public_keys )}}"
      path='/home/{{ item }}/.ssh/authorized_keys'
      manage_dir=no
    become: true
    with_items:
      - '{{rootuser}}'


