---
- hosts: chh-dev
  user: cch_admin

  vars_files:
    - vars/vagrant_variables.yml

  vars:
    adminuser: 'cch_admin'
    adminpassword: 'gyACXJaQZC2L'
  tasks:
  # Setup to users on the ffw-test server
  #- name: Setup | create user chh_admin and chh_cms
  #  command: useradd -m {{ item }} creates=/home/{{ item }}
  #  become: true
  #  become_method: sudo
  #  with_items:
  #    - chh_admin
  #    - chh_cms

  # Setup passwords for both user 'ffw_admin' and 'ffw_user' on our ffw-test server
  #- name: Setup | set passwords for chh_admin and chh_user
  #  shell: usermod -p $(echo '{{ item.createpassword }}' | openssl passwd -1 -stdin) {{ item.createuser }}
  #  become: true
  #  become_method: sudo
  #  with_items:
  #    - { createpassword: 'gyACXJaQZC2L', createuser: 'chh_admin' }
  #    - { createpassword: 'MyVroGJPMdP2', createuser: 'chh_cms' }

  # Setup an public key for this remote machine by copying the public key of this machine to the remote machine.
  # We need to have our id_rsa.pub file within the vars directory of this setup.yml file.
  - name: Add My Public Key To CMS and Admin Users
    authorized_key: user={{ item }}
      key="{{ lookup('file', ubuntu_common_deploy_public_keys )}}"
      path='/home/{{ item }}/.ssh/authorized_keys'
      manage_dir=no
    become: true
    with_items:
      - chh_admin
      - chh_cms

  # Add our admin user to the 'sudo' users file.
  #- name: Sudoers | update sudoers file and validate
  #  lineinfile: "dest=/etc/sudoers
  #    insertafter=EOF
  #    line='{{ adminuser }} ALL=(ALL) NOPASSWD: ALL'
  #    regexp='{{ adminuser }} ALL=(ALL) NOPASSWD: ALL'
  #    state=present"
  #  become: true

