---
- hosts: alfaES1-7 #all
  sudo: true

  vars_files:
    - vars/vagrant_variables.yml


  tasks:

    - name: Installing Java Open JDK
      #apt: name=openjdk-8-jdk state=present
      apt: name=openjdk-7-jre state=present

    - name: Install ElasticSearch 1.7 from our 'deb' file.
      apt: deb="/home/vagrant/alfacms/elasticsearch-1.7.5.deb"
      #sudo: true

    - name: Start ElasticSearch Engine
      service: name=elasticsearch state=started enabled=yes

    - name: Install a repo for Kinaba 4.1
      apt_repository: repo='deb https://packages.elastic.co/kibana/4.1/debian stable main' state=present filename='kibana' validate_certs=no

    - name: update apt cache and key ring for Kiban
      apt: update_cache=yes

    - name: Install Kibana from Apt
      apt: name=kibana state=present allow_unauthenticated=yes
      #ignore_errors: yes

    - name: marvel | Removing Marvel Plugin if it exists
      shell: bin/plugin --remove marvel
        chdir={{ elasticsearch_home_dir }}
      ignore_errors: yes

    - name: marvel | Installing Marvel Plugin - latest version for this ES instance
      shell: bin/plugin -i elasticsearch/marvel/{{ elasticsearch_plugin_marvel_version }}
        chdir={{ elasticsearch_home_dir }}
      register: marvel_plugins_installed
      changed_when: "'Installed' in marvel_plugins_installed.stdout"
      failed_when: "marvel_plugins_installed.rc != 0 and marvel_plugins_installed.stdout.find('already exists. To update the plugin') == -1"








